In [4]:
import pandas as pd
import os
import shutil

In [5]:
dir_name = 'phen2gene'
if os.path.exists(dir_name):
    print("Directory '%s' exist" %dir_name)
else:
    os.mkdir('phen2gene')
    print("Directory '%s' created" %dir_name)

Directory 'phen2gene' exist

In [6]:
# read test patients
test_patients = pd.read_csv('patient_testing.tsv', sep = '\t', header=None)
for patient in test_patients.values.tolist():
    file_name = patient[0].split(':')[1]
    file_path = os.path.join(dir_name, file_name)
    hpos = '\n'.join(patient[3].split(','))
    with open(file_path, 'w') as f:
        f.write(hpos)
test_patients

,0,1,2,3,4,5,6
0,Patient:37083,OMIM:614749,Entrez:84720,"HP:0003155,HP:0001263,HP:0000286,HP:0000215,HP...",Dr. Peter Krawitz,pedia,8
1,Patient:204249,OMIM:602849,Entrez:2261,"HP:0001263,HP:0001250,HP:0001249,HP:0011317,HP...",Nurulhuda Hajjir,pedia,5
2,Patient:29999,OMIM:615716,Entrez:93210,"HP:0003155,HP:0000322,HP:0000215,HP:0001249,HP...",Dr. Peter Krawitz,pedia,5
3,Patient:208664,OMIM:150250,Entrez:2317,"HP:0009836,HP:0001374,HP:0002948,HP:0001222,HP...",Stanislav Rosnev,pedia,13
4,Patient:208654,OMIM:150250,Entrez:2317,"HP:0030310,HP:0004976,HP:0011849,HP:0012758,HP...",Stanislav Rosnev,pedia,22
...,...,...,...,...,...,...,...
4812,Patient:berlin_10,unknown,Entrez:23476,"HP:0000047,HP:0001263,HP:0001252,HP:0007328",berlin,berlin,4
4813,Patient:berlin_11,unknown,Entrez:8398,"HP:0001250,HP:0000717",berlin,berlin,2
4814,Patient:berlin_12,OMIM:617228,Entrez:4285,"HP:0001263,HP:0000508,HP:0001252,HP:0004322,HP...",berlin,berlin,5
4815,Patient:berlin_13,OMIM:615438,Entrez:51520,"HP:0000407,HP:0001263,HP:0012447,HP:0004856,HP...",berlin,berlin,7
4816,Patient:berlin_14,OMIM:611093,Entrez:7991,"HP:0000750,HP:0003781,HP:0010877,HP:0002317",berlin,berlin,4

In [8]:
####run phen2gene manually and save result to phen2gene/out
evaluation = []
for patient in test_patients.values.tolist():
    patient_name = patient[0].split(':')[1]
    target_gene = patient[2].split(':')[1]
    result_path = os.path.join(dir_name, 'out', dir_name, patient_name, 'output_file.associated_gene_list')
    result_pd = pd.read_csv(result_path, sep = '\t', header = 0, dtype = str)
    try:
        rank = int(result_pd.loc[result_pd['ID'] == target_gene, 'Rank'].iloc[0])
    except IndexError:
        rank = 'NA'
    evaluation.append([patient[0], patient[2], patient[3], rank])
    
eval_df = pd.DataFrame(evaluation, columns = ['patient_id', 'gene_id', 'features', 'rank'])
eval_df

,patient_id,gene_id,features,rank
0,Patient:37083,Entrez:84720,"HP:0003155,HP:0001263,HP:0000286,HP:0000215,HP...",88
1,Patient:204249,Entrez:2261,"HP:0001263,HP:0001250,HP:0001249,HP:0011317,HP...",1
2,Patient:29999,Entrez:93210,"HP:0003155,HP:0000322,HP:0000215,HP:0001249,HP...",96
3,Patient:208664,Entrez:2317,"HP:0009836,HP:0001374,HP:0002948,HP:0001222,HP...",1
4,Patient:208654,Entrez:2317,"HP:0030310,HP:0004976,HP:0011849,HP:0012758,HP...",1
...,...,...,...,...
4812,Patient:berlin_10,Entrez:23476,"HP:0000047,HP:0001263,HP:0001252,HP:0007328",16767
4813,Patient:berlin_11,Entrez:8398,"HP:0001250,HP:0000717",449
4814,Patient:berlin_12,Entrez:4285,"HP:0001263,HP:0000508,HP:0001252,HP:0004322,HP...",10936
4815,Patient:berlin_13,Entrez:51520,"HP:0000407,HP:0001263,HP:0012447,HP:0004856,HP...",11180
4816,Patient:berlin_14,Entrez:7991,"HP:0000750,HP:0003781,HP:0010877,HP:0002317",586

In [9]:
# count top-n accuracy 
ranks = eval_df['rank'].tolist()
count1 = count5 = count10 = count50 = count100 = count1000 = 0
counts = len(ranks)
for rank in ranks:
    if isinstance(rank, int):
        if rank == 1:
            count1 += 1
        if rank <= 5:
            count5 += 1
        if rank <= 10:
            count10 += 1
        if rank <= 50:
            count50 += 1
        if rank <= 100:
            count100 += 1
        if rank <= 1000:
            count1000 += 1
top1 = round(count1/counts, 2)
top5 = round(count5/counts, 2)
top10 = round(count10/counts, 2)
top50 = round(count50/counts, 2)
top100 = round(count100/counts, 2)
top1000 = round(count1000/counts, 2)

print(f'top1: {top1}')
print(f'top5: {top5}')
print(f'top10: {top10}')
print(f'top50: {top50}')
print(f'top100: {top100}')
print(f'top1000: {top1000}')

top1: 0.1
top5: 0.23
top10: 0.3
top50: 0.49
top100: 0.57
top1000: 0.74